// Pixel art from Kenney's "Tiny Farm" pack (kenney.nl), CC0 license. Crop
// icons themselves are emoji (matches the rest of this app); this pack
// contributes the plot soil texture and tool icons. See
// star-hopper-sprites.ts for why these are inlined as base64 data URIs
// rather than served from a public/ folder.
export const FARM_SPRITES = {
  soil: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAj0lEQVR42mNsOZb5n4ECwMRAIRh4A1jQBUzm3yTPAFwaxWWFGBgYGBhePn6H2wBkzTANuAzCGwbIiqSVJRiklSUIByK603E5lehAhLni3IFrcD7MUGzeYMFlMi4/4w0DXM4XlxXCaSDLmUR1lFjAFwbYopSFlADDZjgTAwMDw5lEdcrzwplEdZwGwcSxyQMAP9osXG3AgnkAAAAASUVORK5CYII=",
  wateringCan: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAyUlEQVR42mNgGGjAiE/SXs3wP4x98NZ5RpwGICskBNANYiKkuXHpagxXwTADAwMDE7JCGMamEZ0PM4wJWWDS1AUMDAwMDD6lzXA2slzj0tUMwlbeDD6lzQgvICvKy04gGAZvj21F4cMNqI8OZTh94QbDpKkLGEwNNOAKTl+4QTgakQNS2MqbwdLaAm7I6Qs3UNjHj55gsLS2YNjSXYuaDmCGwAzABWAasYYBNj8SShNM2BIIui3YxGHqGfElX2JSIxOhpEqqPMkAAAosWVYGXxw9AAAAAElFTkSuQmCC",
  hoe: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAt0lEQVR42mNkQAP2aob/GfCAg7fOMyLzmUjRjE0NIzaJxqWrsWqujw7FcAkTuiJcmnHJsWBTeObiTawGmOirY4gxEasZlxwTvgAzNdBgMDXQwBuoTAwUAoww2NxVA2e/EmVlYGBgYDj5+jdhF6AnEAYGBgYPQ2EGD0NhvImJCV8qIzklIoMWVRYG1vtvGFjvv2FoUWUhLxCrrv1gqLr2g7RARAZtWhykxwIM1Nz+Q1Q0MhEKJEJyAGkUPJRzP3OjAAAAAElFTkSuQmCC",
  // Standing farmer (tile 108) and market table (tiles 98-99), used by the
  // walkable-world version of Farm.tsx.
  player: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVR4nGNgoBAwogvYqxn+x6fh4K3zKHqYSNGMTQ0jNglzUVYGd0MRFI07z79hOPn6N4ZLUFyASzMDAwODu6EIg7koK4Y4hgEwzVZhFijiVmEWWA1mwRBB0ozNEIZd6/G7AKZJP/MQijg6H6cLXt14zCCmIQtno8uhA6yxsKjEhIGBgQFuEExzXM8ZOB8WC4zomjfHGTIk3JFiyOY5h2LT1C9GDAtUnjH4LjqPYggLumYYMJWQQHXrHYQamCH2aob/4WGwY04gAwMDA8OZzs0MDKJSDAl3pDD8e/H4ZQaTcl+GHXYKDB4pkNjAiIWa238wNOKTY8SW/oWtvBkYGBgY3h7bipWPDJjQcxcDAwNDNs85lEBE58PAwVvnGQF4mmYNDcr+UwAAAABJRU5ErkJggg==",
  table: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAQCAYAAAB3AH1ZAAAAzElEQVR4nGNkgAJ7NcP/DHQEB2+dZ2RgYGBgGgjLke1kQRasc5Nk0LVUoqnFl4/fY2ja9RzOZ0KW1LVUYrh8/B5NLUf3IAu6Il1LJYbQxqM0ccDqemsMMQwHwICFEBMuKbLAiXf/sIrjdICbiTh1HYAU78iAut4kAwy4AzCi4PLxe1gTC6VgNTSHoecClBDApoCaAFs2RwkBx9ggmlkOt0PFgKFp11TsDti/eB3NHYAOBlcihJXRsEIIV+FBKsBnHtYQcDMRp2pBhM88AL08Oox9fiY+AAAAAElFTkSuQmCC",
} as const;
